### ISSUE TITLE
Unclear from the readme on how to connect to hass through Nabu Casa Cloud

### ISSUE THREAD

**Issue by zigt1301** [MarkAdamson/home-assistant-plugin-for-tasker#11]
I am having a rough time properly configurating the plug-in for the second time (I accidentally deleted the working config) and would appreciate it if a little more details were provided. 

Like what the base url would be when you use hass Cloud. It could make it a little more easy for a person like myself to configurate the plug-in.

**Comment by MarkAdamson** [comment]
Hi @zigt1301.

Your base URL when using hass cloud should be the exact one shown when you enable 'Remote Control' in the HA UI - eg:

https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.ui.nabu.casa

That is _without_ the trailing `/`. You should be able to test this readily enough in the add/edit server screen.

One issue you'll probably run into is that any pre-existing actions won't know to use your newly setup server (even if it's named and configured exactly the same as before). You should see an error message to that effect when you attempt to test the task in Tasker. To fix this, you need to go into every one of your actions, ensure the "new" server is selected (it should default to it), then hit back to save the configuration with the new server.

Let me know if this resolves it for you. You're right though, I should probably add something to the readme about this.

**Comment by zigt1301** [comment]
Thank you for the information. It turned out I already had the right Base URL but somehow it wouldn’t connect last night. It does connect now. Could be that it couldn’t reach HASS because I disable Remote UI while I’m home.

Thanks for the timely reaction to my opening of an issue. I’m liking the Plug-IN and will happily provide fmore eedback.

On 12 Jul 2019, at 17:14, MarkAdamson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @zigt1301<https://github.com/zigt1301>.

Your base URL when using hass cloud should be the exact one shown when you enable 'Remote Control' in the HA UI - eg:

https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.ui.nabu.casa<https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.ui.nabu.casa/>

That is without the trailing /. You should be able to test this readily enough in the add/edit server screen.

One issue you'll probably run into is that any pre-existing actions won't know to use your newly setup server (even if it's named and configured exactly the same as before). You should see an error message to that effect when you attempt to test the task in Tasker. To fix this, you need to go into every one of your actions, ensure the "new" server is selected (it should default to it), then hit back to save the configuration with the new server.

Let me know if this resolves it for you. You're right though, I should probably add something to the readme about this.

**Comment by MarkAdamson** [comment]
Yep, that will be why :) I would just leave it enabled if I were you, I doubt there's any harm.

No problem - glad you're liking it :)

**Comment by zigt1301** [comment]
Can I also use the local IP address as a Base URL? Just asking. For now I'm going to take a look at the Get States and Tasker Vars because I would like run certain tasks only if I'm home.

**Comment by MarkAdamson** [comment]
There's no reason it wouldn't work on the plugin side - though I feel like I've read somewhere that HA itself won't work via IP only. All I can really suggest is to try it.

For running tasks only while you're home, there's a couple of ways you could go. You could run a Get State of your person or device_tracker entity, and end the task if it returns "home" - or you could add a "Wi-fi Near" condition to the context in tasker. I'd probably go for the second one myself.
