### ISSUE TITLE
Network error when testing server

### ISSUE THREAD

**Issue by scottsweb** [MarkAdamson/home-assistant-plugin-for-tasker#14]
When adding a server and pressing the test button I see "Network error" returned. 

Device is a Pixel 2 running Android 9.

Let me know if I can help debug this.

**Comment by MarkAdamson** [comment]
Hi,

Can you confirm that your server settings are entered exactly the same as in this [screenshot](https://lh3.googleusercontent.com/YTG2XYkT0dvL6hqj6iAchoVBe7YoE-j-FfTriB_7sUKIXi-aTOd6yRx_ySGwDKEtu1c=w2160-h440-rw), with the protocol (http:// or https://) and no trailing `/`?

Is your home assistant running and accessible at the exact same URL as you enter in the "base URL" field?

**Comment by scottsweb** [comment]
I can confirm they are, the protocol prefix is `http://` and there is no trailing `slash`. Home Assistant is at the same URL.

**Comment by MarkAdamson** [comment]
Can you post logcat from when the error occurs please?

**Comment by scottsweb** [comment]
I haven't been able to retrieve any logs from logcat but I did upgrade to tasker 5.8 and had issues when attempting a standard REST request from an exported APK. It looks like newer Android versions are unable to communicate with http URLs as per: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

I have a feeling this might be the same thing. I am happy to close this issue as I have found a path forwards.

**Comment by MarkAdamson** [comment]
Ah, good find, I didn't know about that!

To be honest, I'll probably add that permission to the app - after all, it's not up to me to police other people's server security.

**Comment by scottsweb** [comment]
Sounds good, I have a number of local APIs running without SSL/TLS. I should get around to working that out soon but it is a low priority :)

**Comment by Migz93** [comment]
Is there still plans to add that permission to the app? Having the same issue when I use a http:// address but if I use my nabu https url it's fine. I usually disable the remote access when I'm home just to close off an unnecessary opening into my network so having your app support just http would be great

**Comment by De4eX** [comment]
I'm also interested in using http://
Any progress on this?
Thanks.

**Comment by scottsweb** [comment]
Because I was exporting my tasker profiles to APKs, I managed to get around this by setting a maximum Andorid version to 21 during the export. The older versions are less fussy about using insecure domains.

**Comment by redlegoman** [comment]
I'm having the same issue. I can't access a http:// link for my local hass server but can use the external https:// link I use for extenal (nginx reverse proxy). Any plans to allow plain http:// ?

**Comment by MarkAdamson** [comment]
This should be resolved in the latest release. See 6870895f5723c78e8404de06a2aed7c2ccd8766e.

Let me know if it's still a problem for anyone.

**Comment by redlegoman** [comment]
> This should be resolved in the latest release. See [6870895](https://github.com/MarkAdamson/home-assistant-plugin-for-tasker/commit/6870895f5723c78e8404de06a2aed7c2ccd8766e).
> 
> Let me know if it's still a problem for anyone.

Is that the version available on the Play Store? I installed from the store today and this was obviously the first problem I had.

**Comment by MarkAdamson** [comment]
I've pushed the update to the play store, but only about 15 minutes ago, so it's unlikely you've got it yet :) version 1.1.5 has the fix in.
