### ISSUE TITLE
Render Template anomaly

### ISSUE THREAD

**Issue by genem2** [MarkAdamson/home-assistant-plugin-for-tasker#15]
This is a great plug-in. I just went through all of my Tasker tasks and replaced all my home assistant calls using this tool. However, I did find something strange with my one instance of render template.

Given the following template:

"It's currently {{ states.sensor. outdoor_temp.state | int }} degrees and {{ states.sensor.dark_sky_summary.state }}. {{ states.sensor. indoor_temp.state | int }} degrees indoors.  Phone is at %BATT %. {% if is_state('input_text.cam_armed_count','0') -%} No ,{%- else -%}{{ states.input_text.cam_armed_count.state }}{%- endif%}{% if is_state('variable.cam_armed_count', '1') -%} camera is {%- else -%}  cameras are {%- endif %} armed. {% set total = states.light|selectattr('state', 'equalto', 'on')|list|length %}{% if is_state('switch.electric_blanket', 'on') %}{% set total = total + 1 %}{% endif %}{% if is_state('switch.family_room_light', 'on') %}{% set total = total + 1 %}{% endif %}{% if is_state('switch.coffee_table', 'on') %}{% set total = total + 1 %}{% endif %}{% if is_state('switch.dresser_mbr', 'on') %}{% set total = total + 1 %}{% endif %}{% if is_state('switch.myblanket', 'on') %}{% set total = total + 1 %}{% endif %}{% if total == 0-%}No {%- else -%} {{ total }}{%- endif %}, devices are on, and I'm seeing you {% if is_state('device_tracker.google_maps_123456789012345678901', 'not_home') -%} away {%- else -%} at {{ states.device_tracker.google_maps_123456789012345678901.state }} {%- endif %}.**DONE**"

The returned variable contains:

"It's currently 83 degrees and Clear. 79 degrees indoors.  Phone is at 99 %. No ,cameras are armed. 1, devices are on, and I'm seeing you at home.**DONE**"_doors.  Phone is at 99 %. No ,cameras are armed._ 

I'm always seeing some replicated content at the end. Maybe I having issue with quoting somewhere?

For now, I am using the Tasker split command to drop everything with that DONE marker.

**Comment by MarkAdamson** [comment]
Hi genem. I've replicated this issue on my setup. It doesn't look like a problem with the quoting - more likely a problem with the string building in the plugin. I'll look into it further.

Thanks for the report, much appreciated :)

**Comment by MarkAdamson** [comment]
Fixed in 1bf1a1a655355b53278cdfec68c2631d18460c30

Thanks again for the report.

**Comment by genem2** [comment]
Thank you.  Assume I await the update via Play.

Gene

**Comment by MarkAdamson** [comment]
Yep :)
