### ISSUE TITLE
New Long Lived token won't save

### ISSUE THREAD

**Issue by GaryOkie** [MarkAdamson/home-assistant-plugin-for-tasker#25]
Hi Mark,

Tasker+HA_plugin has been working great for me the past few months and all of a sudden it has been getting auth failures and getting locked out of HA.   I removed the IP_Ban for the phone, restarted HA, and created a new LL Token  and pasted it into the Access Token field - no problem. 

But upon "Test Server", the app gives a "_network error - Unauthorized_" and HA immediately logs an invalid login.    But here's the strange thing- the Access Token in the plugin reverts to the original LL token (which was now deleted from HA) and I assume that is what it is trying to login with.

I have cleared the plugin's cache as well as un/reinstalled the plugin and the problem repeats.    I simply cannot get the new token saved.   Do you have any advice or debugging tips that can help?

EDIT:

I also just now tried creating a whole new server, with name/baseurl/token and after tapping Test Server, this new server entry also disappears and is not saved!   Is there a flat text config file  that I can hack to enter and save this info?   (Android 7.1.2.  Latest version of Tasker and plugin)

Yet Another EDIT:

Cleared app cache and data for both the plugin and Tasker, UNINSTALLED them both, rebooted, and reinstalled.  Now setting up the configurations all over again and was quite surprised to see that the original HASS Server/url information and original invalid token were remembered, but nothing else was.   Still can't change the token.

**Comment by GaryOkie** [comment]
Completely wiped the phone that was dedicated for tasker/HASS automation and started over from scratch.  Reinstalled everything.   Now when attempting to add a new server config in the plugin, and after all entered properly, tapping "Test Server" just clears the screen with absolutely nothing saved and no errors on screen.

This is not unique to a single instance of HASS. Set up a new token on a different HASS instance and the exact same thing occurs.   (Both are externally accessible via DuckDNS/https certs).

This plugin is completely busted for me now and I wish there was some advice on how to debug it.

**Comment by GaryOkie** [comment]
Apparently the problem all along was saving the token in a google drive text file to simplify copy/paste between PC and phone.  The token had hidden CR/LF's in it.    This is surely why the token would not save.    Sure would have been nice if there was an internal error preventing the save, the app would shout about it.

I only found out about this by using the "HTTP Shortcuts" Android Restful app which in fact did holler that an unexpected character 0xD encountered in the token.

I'll leave this open as an enhancement request to add a small bit of error checking if that is at all possible.

**Comment by hathalud** [comment]
I recently installed the plugin for the first time ever and it's giving me the same errors. Found the above hypothetical solution and tried directly copying and pasting a new key... still giving the same network unauthorized error.

**Comment by wmillea** [comment]
Did you ever resolve the Network Error issue?  I'm having the same problem and I'm stumped. 



> I recently installed the plugin for the first time ever and it's giving me the same errors. Found the above hypothetical solution and tried directly copying and pasting a new key... still giving the same network unauthorized error.

**Comment by GaryOkie** [comment]
I solved my particular network unauthorized problem and inability to save the token by ensuring a clean copy/paste of the token.  However,  I no longer use this tasker plugin.   It does simplify the setup a little bit but it's not really needed.  The tasker template documented in the HA forum provides a direct means of including the same data fields.

Also note that if you use the HA Companion Android app, it now provides the same feature to trigger actions upon phone notifications.   The iOS HA Companion may as well, but I have not used it.

In any case, this was an enhancement request for improved error checking.   Since I don't use this plugin any more, I'll close this.
