### ISSUE TITLE
Network error: unauthorized

### ISSUE THREAD

**Issue by vampirete** [MarkAdamson/home-assistant-plugin-for-tasker#28]
Hi.

I have found this plugin and I love tasker. I have tried to add server but could not. When I do "test service" it appear the message "Network error: unauthorized"

Should the server name be a concrete name?

Have I to do something more?

Thanks

> Logger: homeassistant.components.http.ban
Source: components/http/ban.py:114
Integration: HTTP (documentation, issues)
First occurred: 22:14:13 (1 occurrences)
Last logged: 22:14:13
Login attempt or request with invalid authentication from localhost (127.0.0.1) (Dalvik/2.1.0 (Linux; U; Android 10; HD1903 Build/QKQ1.190716.003))

![Screenshot_20201119-221724~2](https://user-images.githubusercontent.com/68235482/99726121-61505080-2ab6-11eb-937a-fa14008d27d7.jpg)

**Comment by vontrapp** [comment]
I have the same problem. What was the solution?

**Comment by GGServersDevelopment** [comment]
^Same here, any solution?

**Comment by MitchTalmadge** [comment]
Also running into this problem. Tried new tokens with no success.

**Comment by GGServersDevelopment** [comment]
Using an older older token worked, seems like the problem is actually with
new tokens
