### ISSUE TITLE

Json error

### ISSUE THREAD

**Issue by El-mou33** [MarkAdamson/home-assistant-plugin-for-tasker#38]
The plugin show me this 2 errors. I can't use the plugin, for me it's impossible to make it work.

![Screenshot_2022-06-28-01-37-01-290_com.markadamson.taskerplugin.homeassistant.jpg](https://user-images.githubusercontent.com/90722688/176054344-39e95ebd-a817-45bb-8eab-95bbd6eb1366.jpg)

![Screenshot_2022-06-28-01-37-08-160_com.markadamson.taskerplugin.homeassistant.jpg](https://user-images.githubusercontent.com/90722688/176054358-82c1e7fa-3519-49df-b096-0b8314de7ea2.jpg)

**Comment by ITensEI** [comment]
The format should be { "entity_id": "switch.regleta_mediana_socket_3" }

**Comment by El-mou33** [comment]
THANKYOU!!!!!!!!
