### ISSUE TITLE
Get an entity state

### ISSUE THREAD

**Issue by MarkAdamson** [MarkAdamson/home-assistant-plugin-for-tasker#4]
It would be good to be able to retrieve the state of an entity to use within a task.

**Comment by MarkAdamson** [comment]
Implemented in commit bc1f1c6.

**Comment by dale3h** [comment]
I might be overlooking something super simple, but I cannot seem to get the state of an entity into a Tasker variable for use in a task. The test button on the **Get State** configuration screen works fine and shows the correct state.

- On the "Get State" configuration screen, does the **Variable** field relate to a Tasker variable?
- If so, should I include the leading `%` in the variable name?

I have also tried accessing the value using `%ret`, but the test popup just shows the literal string `%ret`. The same happens with any variable name that I try.

**Use case:** I have an Android head unit in my Jeep, and would like to set the screen brightness based on the state of `sun.sun`. I have previously used time profiles, but find myself adjusting the times every few weeks to keep up with approximate sunrise/sunset.

**Comment by MarkAdamson** [comment]
Hi Dale,

It's not super obvious, but you need to set a timeout on the 'Get State' action, to allow the task to await the result before continuing. Otherwise it carries on instantly without actually retrieving the result into the variable. I really should add this to the readme.

Let me know if that does it for you.

**Comment by MarkAdamson** [comment]
Btw, to answer your questions:
- Yes, the **Variable** field does relate to a Tasker variable.
- Yes, you should include the leading `%` in the variable name.

HTH :)

**Comment by genem2** [comment]
I'm not seeing this either. plug-in: 1.0.4.   HA: 0.94.3,  Tasker: 5.7.2 

>     Plugin Test (44)
>     	A1: Get State [ Configuration:sensor.outdoor_temp Timeout (Seconds):208 ] 
>     	A2: Flash [ Text:%ot Long:Off ] 
>     	A3: Call Service [ Configuration:notify.join_tablet Timeout (Seconds):1 ] 
> 

Note that A1 doesn't reflect the output variable (%ot). Ok, fine, but entering A2, Tasker isn't listing the variable as an option, either. I came seem to get anything back. Testing step A1 toasts the temperature just fine. Step A3 works perfectly.
Thoughts?

**Comment by MarkAdamson** [comment]
Hmm. Ok @genem2, and I assume you're getting the same issue as dale, where the toast in A2 just displays '%ot', not the sensor reading?

Could you check over [this list](https://tasker.joaoapps.com/userguide/en/faqs/faq-problem.html#00) and make sure you've applied the appropriate battery optimization settings to both Tasker and the plugin?

208 seconds is a long timeout on step A1 - it's a simple API call that really shouldn't take more than a second or so. When you run the task, does step A1 take the full 208 seconds and timeout? Does it seem to return instantly? Or does it take a normal-seeming amount of time - say 0.5 - 2 seconds?

**Comment by genem2** [comment]
So sorry, I was editing the comment to include what I found...

My Flash was not appearing - at all - because Tasker had Notifications disabled. However two things users have to remember: Everytime you _configure_ the plug-in's task, Tasker resets the timeout back to zero. Also, the variable you're configuring in the task will not appear as a variable in Tasker selection screens until you enter it into another task. But for now, it's working for me. Thank you.

**Comment by MarkAdamson** [comment]
Good stuff - no worries, that damn timeout reverting to zero has caught me out a few times too! Glad it's working for you now :)

**Comment by MarkAdamson** [comment]
Hi @dale3h - same questions as for genem2:
* Could you check over [this list](https://tasker.joaoapps.com/userguide/en/faqs/faq-problem.html#00) and make sure you've applied the appropriate battery optimization settings to both Tasker and the plugin?
* When you run the task, does the 'Get State' action take the full timeout and error, does it seem to return instantly, or does it take a normal-seeming amount of time - say 0.5 - 2 seconds?

**Comment by genem2** [comment]
> battery optimization 

I never thought about that, but have now removed it from optimization 
>  'Get State' action

I experience what you're classifying as normal. I get the value bach right way when it's working, otherwise it blocks for the timeout time.

BTW: Yesterday I've noticed there were times when things just not communicating. If I open the task and press the play icon in Tasker, it blocks on my first entry (sensor.indoor_temp) ane errors out with:
```
15.02.50/E FIRE PLUGIN: Get State / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 7 bundle keys
15.02.50/E Get State: plugin comp: com.markadamson.taskerplugin.homeassistant/com.markadamson.taskerplugin.homeassistant.receiver.FireReceiver
15.02.50/E add wait type Plugin1 time 10
15.02.50/E add wait type Plugin1 done
15.02.50/E add wait task
15.03.00/E Error: null
```
If open the offending statement and [test] it inside the component's screen, it always executes as expected and toasts the proper value.  If I back out of the component and press Play in Tasker again, it again times out with that error.  Or, if go to another line in that task to get sensor.outdoor_temp, it always works. I let it go at that point... ;-)

**Comment by MarkAdamson** [comment]
Huh, that's really strange. So you're saying that fetching sensor.indoor_temp on the first line sometimes fails, but fetching sensor.outdoor_temp on another line always succeeds?

That's really confusing... Can you try and find out if maybe the problem only affects actions on the first line?

I'm at a bit of a loss I'm afraid. I'm planning to get this on the play store at some point, then I'll be able to receive the actual logcat errors, which might shed some light on the problem - until then I'm a bit stumped :(

**Comment by genem2** [comment]
Agreed, strange. I wasn't going to write you about it until I had a better handle on it, myself. It's not feeling at this moment, but next time it does I'll investigate further and see what I can find.

**Comment by dale3h** [comment]
I have searched everywhere, but my device does not have battery optimization settings enabled. It has no internal battery, runs from my Jeep’s battery.

It has never taken the full timeout, and always seems to take a normal amount of time. I have tried adding more lines to get other entities, but still no luck.

Until today, I was still using 1.0.3. Upgraded to 1.0.4 and still broken.

I do have log set to display on Tasker open, and I am getting some errors to that log:

```
Plugin: 14.55.52#Plugin: warning: getReturnedVars: invalid variable name: %SunState
Plugin: 14.55.52#Plugin: warning: getReturnedVars: invalid variable name: %pd
Plugin: 14.55.53#Plugin: warning: getReturnedVars: invalid variable name: %tm
```

- `%SunState` = trying to get state of `sun.sun`
- `%pd` = trying to get state of `person.dale`
- `%tm` = trying to get state of `sensors.time`

**Comment by dale3h** [comment]
As for the other settings mentioned in that link, I have applied as many that were available to do on my device (Seicane 10.1” Android 7.1 Jeep Wrangler head unit)

**Comment by MarkAdamson** [comment]
@dale3h, I think I can help with those - afaik, tasker variables must be at least three characters long, and variables returned from plugins must be all lowercase. Try changing your vars to:
* %sunstate
* %dale
* %time

And see if it works.

**Comment by dale3h** [comment]
I think I tried `%sunstate` without success, but I will definitely give it try and let you know! Thank you again!

**Comment by genem2** [comment]
FWIW: I also wrestled with this variable issue, which lead me to this thread. I never realized that Tasker was reseting the timeout value everyone time I made a change to the plug-in. Once learned, I revisited all my other plug-in calls, fixing them too.

**Comment by MarkAdamson** [comment]
Btw, the latest build fixes the timeout issue, and tidies up the variable handling generally. It's not in a release yet, but the [apk](https://github.com/MarkAdamson/home-assistant-plugin-for-tasker/raw/master/HomeAssistantTaskerPlugin/HomeAssistantTaskerPlugin-release.apk) is available.

**Comment by genem2** [comment]
Whoa! Nice update (1.0.5). Default setting of timeout! Variables now selectable when entering next commands!  This thing rocks.
