### ISSUE TITLE
Plugin not working from within Tasker / Error:null

### ISSUE THREAD

**Issue by dannyqwertz** [MarkAdamson/home-assistant-plugin-for-tasker#6]
I have problems getting this plugin to run.

I can call services and get states from within the plugin configuration (via "Test service" and "Test entity" buttons) but getting an error when performed in a task.

![576-1024](https://user-images.githubusercontent.com/3381961/60168954-0e616380-9806-11e9-8b89-65f8a790481a.png)

![576-1025](https://user-images.githubusercontent.com/3381961/60168953-0e616380-9806-11e9-8d35-02c694ef1b5f.png)

Log:

`06-26 11:17:52.655 E/AndroidRuntime(11848): FATAL EXCEPTION: AsyncTask #1
06-26 11:17:52.655 E/AndroidRuntime(11848): Process: com.markadamson.taskerplugin.homeassistant, PID: 11848
06-26 11:17:52.655 E/AndroidRuntime(11848): java.lang.RuntimeException: An error occurred while executing doInBackground()
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.lang.Thread.run(Thread.java:764)
06-26 11:17:52.655 E/AndroidRuntime(11848): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.markadamson.taskerplugin.homeassistant.iq.b' on a null object reference
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at com.markadamson.taskerplugin.homeassistant.im.a(SourceFile:3024)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at com.markadamson.taskerplugin.homeassistant.service.ActionService.a(SourceFile:46)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at com.markadamson.taskerplugin.homeassistant.ay$a.doInBackground(SourceFile:2391)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-26 11:17:52.655 E/AndroidRuntime(11848): 	... 3 more
`

**Comment by MarkAdamson** [comment]
Hi - I see that you're using variables with capital letters. This doesn't seem to work with plugins, I think it may be a limitation of Tasker. Please could try changing the variables to all lower case, and see if it helps?

I should probably put some validation checking here.

**Comment by lowfat32** [comment]
I believe I am having the same issue. If I do a 'test service' insider the task it works every time. And if I run the profile/task immediately afterward it works.  But beyond that I haven't been able to get it to work properly. All I am doing is toggling an input boolean. Have no capital letters in the input_booleans name. 

08.35.15/E FIRE PLUGIN: Call Service / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 7 bundle keys
08.35.15/E Call Service: plugin comp: com.markadamson.taskerplugin.homeassistant/com.markadamson.taskerplugin.homeassistant.receiver.FireReceiver
08.35.15/E add wait type Plugin1 time 6
08.35.15/E add wait type Plugin1 done
08.35.15/E add wait task
08.35.21/E Error: null

**Comment by MarkAdamson** [comment]
Hi @lowfat32 - this may be to do with battery optimization. Please could you check over [this list](https://tasker.joaoapps.com/userguide/en/faqs/faq-problem.html#00) and ensure the plugin is not being optimized by Android?

@dannyqwertz - please could you also double check this?

**Comment by dannyqwertz** [comment]
Battery optimisation is disabled for plugin and tasker, sadly no difference here.

Problem also persists when using direct service call and service data in the task. (light.toggle and a respective entity_id)

Problem doesn't occur when using the "test buttons", this switches lights on and off and also responds correct states.

Your plugin worked perfectly before (1.04), yesterday my saved home assistant credentials where gone so I added them again, which since then throws the errors above (meanwhile uninstalled plugin und reinstalled new 1.10, but the error persists)

**Comment by MarkAdamson** [comment]
@dannyqwertz, if your credentials disappeared, or you uninstalled/reinstalled, then they'll have gotten unlinked from your actions. You'll need to enter and exit (press back, not cancel) the config screens for all your actions. This should relink them.

Let me know if this helps.

**Comment by dannyqwertz** [comment]
@MarkAdamson I tried that already, and just now created a whole new task to test again, but same problem persists: Working as it should from within your plugin but throwing error when task is performed in tasker (see attached screenshots)

When performing the task (via play button I circled in screenshot) it takes the set timeout time to run and then throws Error: null

![Screenshot_1](https://user-images.githubusercontent.com/3381961/60200066-a468ae80-9845-11e9-8c34-85797133a705.png)
![Screenshot_2](https://user-images.githubusercontent.com/3381961/60200069-a6cb0880-9845-11e9-816f-dc64ee2139c2.png)

**Comment by MarkAdamson** [comment]
@dannyqwertz could you try 'Force Stop' the plugin from the App Info screen, then re-enter Tasker and test the task again please?

**Comment by dannyqwertz** [comment]
@MarkAdamson I may got it working again now - think the problem after all was this: 

> @dannyqwertz, if your credentials disappeared, or you uninstalled/reinstalled, then they'll have gotten unlinked from your actions. You'll need to enter and exit (press back, not cancel) the config screens for all your actions. This should relink them.

I had some tasks running in Tasker which are updating the states of some devices on "screen on" and I didn't re-link the newly entered credentials in this corresponding tasks. My assumption is this somehow also fucked up the newly created tasks which I was using to debug this error .. 🤔 

Maybe there is a way to output a more meaningful error-message when this is the case? (missing server credentials?)

I think the plugin also auto-selects the newly created server (when its the only entry) when editing an existing action which was linked with another server before? Maybe this explains why I needed some time to get behind the problem 😄

I'll close this issue if that was finally the problem and otherwise will go on fiddling around and report back!


Thanks for your work dude, I really stepped up my smarthome-android-game the last days because of your plugin!


![Screenshot_3](https://user-images.githubusercontent.com/3381961/60202980-01676300-984c-11e9-8cb0-daa208919ee7.png)

**Comment by MarkAdamson** [comment]
Haha, no worries, glad you're liking it! Leave the issue open though, cause you're right, it needs a better error message, and there should also be a warning before deleting servers since the results can be so dire...

**Comment by MarkAdamson** [comment]
Opened issues #8 and #9 to address this. Thanks for the bug report @dannyqwertz.

@lowfat32, I believe your issue is the same as #5 - the resolution for which is #7. Please open a new issue if you're still having problems.

**Comment by lildevilx** [comment]
Hey @dannyqwertz I seem to be getting the exact same error you are, however as you suggested, i've tried to enter into the config, and hit the back button to back out to the task list, but I'm still having the same error. Is that all you had to do? did you do anything else to get this working?

Thanks!
